#save dulu jika mau run docker-compose

volumes:
  mongo-data:
    name: mongo-data
  mongo-data1:
    name: mongo-data1

networks:
  networks-example:
    name: networks-example
    driver: bridge

services:
  #ini adalah contoh service yang menggunakan image nginx:latest
  nginx-example:
    image: nginx:latest
    container_name: nginx-example
    #short syntax
    ports:
      - "8080:80"
    networks:
      - networks-example

  nginx-example2:
    image: nginx:latest
    container_name: nginx-example2
    #long syntax
    ports:
      - protocol: tcp
        target: 80
        published: 8081
        mode: host

  #ini adalah contoh service yang menggunakan image mongo:latest
  mongo-example:
    image: mongo:latest
    container_name: mongo-example
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
    #shot syntax
      - "./data-mongo:/data/db"
    networks:
      - networks-example

  mongo-example1:
    image: mongo:latest
    container_name: mongo-example1
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
    #long syntax
      - type: bind
        source: "./data-mongo1"
        target: "/data/db"
        read_only: false
  
  mongo-example2:
    image: mongo:latest
    container_name: mongo-example2
    ports:
      - "27021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
    #shot syntax
      - "mongo-data:/data/db"

  mongo-example3:
    image: mongo:latest
    container_name: mongo-example3
    ports:
      - "27022:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
    #long syntax
      - type: volume
        source: "mongo-data1"
        target: "/data/db"
        read_only: false

  mongo-express-example:
    image: mongo-express:latest
    container_name: mongo-express-example
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-example #container name
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - networks-example
    depends_on:
      - mongo-example #service name